import { createFileRoute } from "@tanstack/react-router";
import { useState, type FormEvent, type ReactNode } from "react";
import {
  ArrowRight, Building2, Check, ChevronDown, CloudRain, Globe2, Headphones,
  Landmark, Leaf, Mail, Menu, Network, Pause, Play, Radio, Satellite,
  ShieldCheck, Sprout, Users, WalletCards, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import heroImage from "@/assets/gonaai-hero.jpg";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "GonaAI | Climate Takaful for African Agriculture" },
    { name: "description", content: "Satellite-driven Takaful protection and local-language climate advisories for African agriculture." },
    { property: "og:title", content: "GonaAI Climate Takaful" },
    { property: "og:description", content: "Protecting African farming seasons with mutual protection and climate intelligence." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: Index,
});

const tabs = [
  { id: "satellite", label: "Satellite triggers", icon: Satellite, headline: "Zero paperwork. Zero delay.", copy: "Satellite intelligence tracks rainfall and soil moisture across Nigerian farms. When a pre-agreed threshold is breached, verified payouts can reach mobile wallets within 48 hours." },
  { id: "pooling", label: "Mutual pooling", icon: ShieldCheck, headline: "Protection owned by the community.", copy: "Participant contributions build a cooperative safety net. The model is transparent, Shariah-compliant, and designed to protect whole agricultural supply chains." },
  { id: "voice", label: "Voice advisories", icon: Radio, headline: "Local insight, in a familiar voice.", copy: "Farmers receive timely planting, fertilizing, and harvest guidance through automated calls in local languages—even on basic feature phones." },
  { id: "dividends", label: "Cash-back dividends", icon: WalletCards, headline: "Good seasons reward everyone.", copy: "When claims stay low, eligible underwriting surplus returns to farmers through mobile money or a credit toward the next season’s contribution." },
] as const;

const featureRows = [
  { icon: Satellite, title: "Satellite-verified protection without paperwork", copy: "Independent climate data verifies weather events automatically, removing delays and expensive field assessments." },
  { icon: ShieldCheck, title: "Ethical protection built around shared responsibility", copy: "No interest, hidden uncertainty, or speculation—only transparent mutual protection for farming communities." },
  { icon: Headphones, title: "Practical guidance delivered in local languages", copy: "Voice calls bring hyper-local weather and agronomic advice to farmers using any kind of mobile phone." },
  { icon: WalletCards, title: "A successful season returns value to farmers", copy: "Eligible surplus is shared as a cash-back dividend or rolled into protection for the next farming season." },
] as const;

function Brand() {
  return <a href="#top" className="flex items-center gap-2" aria-label="GonaAI home">
    <span className="relative grid size-9 place-items-center text-primary"><span className="absolute size-7 rotate-45 rounded-[35%] bg-sun"/><Leaf className="relative size-5"/></span>
    <span className="text-xl font-extrabold">GonaAI</span><span className="text-[10px] font-bold text-muted-foreground">TAKAFUL</span>
  </a>;
}

function Index() {
  const [menu, setMenu] = useState(false);
  const [active, setActive] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [sent, setSent] = useState(false);
  const item = tabs[active] ?? tabs[0];
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setSent(true); };

  return <div id="top" className="min-h-screen bg-background text-foreground">
    <div className="bg-announcement text-announcement-foreground"><div className="mx-auto flex h-9 max-w-7xl items-center justify-between px-5 text-[11px] font-semibold lg:px-8"><span>Climate protection made for African agriculture <a href="#how" className="ml-2 underline">Learn more</a></span><span className="hidden items-center gap-5 sm:flex"><span className="flex items-center gap-1"><Mail className="size-3"/> partners@gona.ai</span><span>Nigeria <ChevronDown className="inline size-3"/></span><span>EN <ChevronDown className="inline size-3"/></span></span></div></div>
    <header className="sticky top-0 z-50 border-b border-border/60 bg-background/95 backdrop-blur"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><Brand/><nav className="hidden items-center gap-2 lg:flex">{[["Home","#top"],["How It Works","#how"],["Our Impact","#impact"],["Ethical Framework","#ethics"],["FAQs","#faqs"]].map(([x,h],i)=><a key={x} href={h} className={`rounded-xl px-4 py-3 text-xs font-bold transition-colors ${i===0?"bg-secondary text-primary":"hover:bg-secondary"}`}>{x}</a>)}</nav><Button className="hidden rounded-xl lg:inline-flex" asChild><a href="#partner">Partner With Us</a></Button><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div>{menu&&<div className="border-t bg-background px-5 py-3 lg:hidden">{[["Home","#top"],["How It Works","#how"],["Our Impact","#impact"],["Ethical Framework","#ethics"],["FAQs","#faqs"],["Partner With Us","#partner"]].map(([x,h])=><a key={x} href={h} onClick={()=>setMenu(false)} className="block border-b py-3 text-sm font-bold">{x}</a>)}</div>}</header>

    <main>
      <section className="relative overflow-hidden bg-primary text-primary-foreground"><div className="pointer-events-none absolute -right-24 -top-24 size-96 rounded-full bg-sun/20"/><div className="pointer-events-none absolute -bottom-32 right-1/3 size-72 rounded-full border-[30px] border-sun/15"/><div className="relative mx-auto grid min-h-[580px] max-w-7xl items-center gap-12 px-6 py-16 lg:grid-cols-2 lg:px-14"><div><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-sun"><Satellite className="size-4"/> Climate intelligence for every season</p><h1 className="text-4xl font-bold leading-tight sm:text-6xl">A climate shock shouldn’t stop a farming season.</h1><p className="mt-6 max-w-lg text-sm leading-7 text-primary-foreground/85 sm:text-base">Satellite-driven Takaful protection and local-language advisories help African farmers recover quickly—and share in the value of a successful season.</p><Button variant="secondary" size="lg" className="mt-8 rounded-xl px-7" asChild><a href="#partner">Partner with us <ArrowRight/></a></Button></div><div className="relative mx-auto w-full max-w-xl"><img src={heroImage} alt="A northern Nigerian farmer using GonaAI climate guidance in her field" className="aspect-[4/3] w-full object-cover object-center shadow-soft [clip-path:ellipse(72%_78%_at_50%_45%)]"/></div></div></section>

      <section aria-label="Partner ecosystem" className="overflow-hidden bg-background py-11"><p className="mb-8 text-center text-xs font-bold">They’re building climate resilience with us</p><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-center gap-x-14 gap-y-7 px-5 text-muted-foreground">{[{icon:Sprout,label:"Farming cooperatives"},{icon:Landmark,label:"Islamic finance"},{icon:Building2,label:"Input suppliers"},{icon:Network,label:"Outgrower networks"}].map(({icon:Icon,label})=><div className="flex items-center gap-2 text-sm font-extrabold" key={label}><Icon className="size-6 text-primary"/>{label}</div>)}</div></section>

      <section id="how" className="relative scroll-mt-28 overflow-hidden bg-primary py-20 text-primary-foreground"><img src={heroImage} alt="GonaAI climate intelligence supporting farmers" loading="lazy" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-primary/95 via-primary/75 to-primary/45"/><div className="absolute inset-0 bg-gradient-to-t from-primary/70 via-transparent to-primary/50"/><div className="relative mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.78fr_1.22fr] lg:px-8"><div><h2 className="max-w-md text-4xl font-bold leading-tight drop-shadow-sm sm:text-5xl">Quick and easy climate protection for every farmer</h2><p className="mt-5 max-w-md text-sm leading-6 text-primary-foreground/80">We’re modernizing agricultural protection to remove the barriers that keep smallholder farmers exposed to unpredictable weather.</p></div><div className="space-y-4">{featureRows.map(({icon:Icon,title,copy})=><article key={title} className="flex gap-5 rounded-2xl bg-primary-foreground/10 p-6 backdrop-blur-sm"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-sun text-primary"><Icon className="size-5"/></span><div><h3 className="font-sans text-sm font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-primary-foreground/75">{copy}</p></div></article>)}</div></div></section>

      <section className="py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-extrabold uppercase text-primary">The protection journey</p><h2 className="mt-3 text-4xl font-bold sm:text-5xl">One connected system, four clear advantages.</h2></div><div className="mt-10 grid gap-7 lg:grid-cols-[.78fr_1.22fr]"><div className="grid gap-2">{tabs.map((tab,i)=><Button key={tab.id} variant="ghost" onClick={()=>setActive(i)} className={`h-auto justify-start rounded-xl px-5 py-5 text-left ${active===i?"bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground":"bg-secondary hover:bg-secondary/70"}`}><span className="mr-4 grid size-9 place-items-center rounded-full bg-background/90 text-primary"><tab.icon className="size-4"/></span><span>{tab.label}</span><ArrowRight className="ml-auto size-4"/></Button>)}</div><article key={item.id} className="panel-enter relative min-h-[340px] overflow-hidden rounded-2xl bg-primary p-8 text-primary-foreground sm:p-12"><item.icon className="size-10 text-sun"/><h3 className="mt-14 max-w-lg text-3xl font-bold sm:text-4xl">{item.headline}</h3><p className="mt-5 max-w-xl text-sm leading-7 text-primary-foreground/75">{item.copy}</p>{item.id==="voice"&&<Button variant="secondary" className="mt-7 rounded-xl" onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play/>}{playing?"Pause advisory":"Hear a sample"}</Button>}<span className="absolute -bottom-16 -right-16 size-52 rounded-full border-[34px] border-sun/30"/></article></div></div></section>

      <section id="impact" className="scroll-mt-28 bg-primary py-20 text-primary-foreground"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-extrabold uppercase text-sun">Our impact</p><h2 className="mt-3 text-4xl font-bold sm:text-5xl">Protection that keeps value in rural communities.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[["100%","Shariah-compliant inclusion"],["0%","Literacy barriers"],["48h","Target payout window"]].map(([metric,label])=><div className="rounded-2xl bg-primary-foreground/10 p-6" key={label}><strong className="text-4xl text-sun">{metric}</strong><p className="mt-8 text-sm font-bold leading-5">{label}</p></div>)}</div></div><div className="mt-12 flex flex-wrap gap-3">{["SDG 1 · No Poverty","SDG 2 · Zero Hunger","SDG 13 · Climate Action"].map(x=><span key={x} className="rounded-full border border-primary-foreground/25 px-5 py-3 text-xs font-bold">{x}</span>)}</div></div></section>

      <section id="ethics" className="scroll-mt-28 bg-secondary py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-xs font-extrabold uppercase text-primary">Ethical framework</p><h2 className="mt-3 text-4xl font-bold sm:text-5xl">Shared responsibility, clearly defined.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-muted-foreground">GonaAI is built around mutual protection—not interest, speculation, or hidden uncertainty.</p></div><div className="space-y-3">{[["No Riba","No interest-based mechanisms."],["No Gharar","Clear thresholds and transparent terms."],["No Maisir","Mutual protection, never speculation."]].map(([h,p])=><div key={h} className="flex items-center gap-4 rounded-2xl bg-card p-5 shadow-soft"><Check className="size-5 text-primary"/><div><h3 className="font-sans text-sm font-extrabold">{h}</h3><p className="mt-1 text-sm text-muted-foreground">{p}</p></div></div>)}</div></div></div></section>

      <section id="faqs" className="scroll-mt-28 py-20"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-extrabold uppercase text-primary">Frequently asked questions</p><h2 className="mt-3 text-4xl font-bold sm:text-5xl">Quick answers for practical deployment.</h2></div><Accordion type="single" collapsible>{([ ["Who can partner with GonaAI?","Agribusinesses, grant funders, Takaful underwriters, cooperatives, input suppliers, lenders, and outgrower networks."], ["How are payouts triggered?","Pre-agreed climate thresholds are monitored by satellite. A verified breach starts the payout workflow."], ["Do farmers need smartphones?","No. Advisories are delivered through local-language voice calls designed for basic feature phones."], ["What happens in a good weather year?","Eligible surplus can return through mobile money or roll over into the next season’s protection."] ] as const).map(([q,a])=><AccordionItem value={q} key={q}><AccordionTrigger className="py-6 text-left font-extrabold hover:no-underline">{q}</AccordionTrigger><AccordionContent className="pr-8 leading-6 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>

      <section id="partner" className="scroll-mt-28 bg-secondary py-20"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="text-xs font-extrabold uppercase text-primary">Partner with GonaAI</p><h2 className="mt-3 text-4xl font-bold sm:text-5xl">Let’s protect the season together.</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">Deploy a development grant, de-risk an outgrower network, or anchor an underwriting pool with infrastructure built for the field.</p></div>{sent?<div className="grid min-h-[420px] place-items-center rounded-2xl bg-primary p-10 text-center text-primary-foreground"><div><span className="mx-auto grid size-14 place-items-center rounded-full bg-sun text-primary"><Check/></span><h3 className="mt-5 text-3xl font-bold">Request received.</h3><p className="mt-3 text-sm text-primary-foreground/70">Thank you. Your collaboration scope is ready for our partnership team.</p><Button variant="secondary" className="mt-7 rounded-xl" onClick={()=>setSent(false)}>Send another request</Button></div></div>:<form onSubmit={submit} className="rounded-2xl bg-card p-6 shadow-soft sm:p-9"><div className="grid gap-x-5 sm:grid-cols-2"><Field label="Name"><input required name="name" className="h-12 w-full rounded-xl border bg-background px-4 outline-none focus:ring-2 focus:ring-ring" placeholder="Your full name"/></Field><Field label="Institutional email"><input required type="email" name="email" className="h-12 w-full rounded-xl border bg-background px-4 outline-none focus:ring-2 focus:ring-ring" placeholder="name@organisation.org"/></Field></div><Field label="I am a..."><select required defaultValue="" className="h-12 w-full rounded-xl border bg-background px-4"><option value="" disabled>Select partnership type</option><option>Agribusiness Grant Donor</option><option>Takaful Underwriter</option></select></Field><Field label="Message / scope of collaboration"><textarea required rows={4} className="w-full resize-none rounded-xl border bg-background p-4" placeholder="Tell us about your programme or target communities."/></Field><Button size="lg" className="mt-2 rounded-xl">Submit & Request Technical Brief <ArrowRight/></Button></form>}</div></section>
    </main>

    <footer className="bg-primary py-14 text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:grid-cols-3 lg:px-8"><div><Brand/><p className="mt-5 max-w-xs text-xs leading-6 text-primary-foreground/65">Climate resilience, mutual protection, and shared prosperity for African agriculture.</p></div><div><p className="text-xs font-extrabold uppercase text-sun">Explore</p><div className="mt-4 space-y-3 text-sm"><a className="block" href="#how">How it works</a><a className="block" href="#impact">Our impact</a><a className="block" href="#faqs">FAQs</a></div></div><div><p className="text-xs font-extrabold uppercase text-sun">Contact</p><p className="mt-4 flex items-center gap-2 text-sm"><Mail className="size-4"/> partners@gona.ai</p><p className="mt-3 flex items-center gap-2 text-sm"><Globe2 className="size-4"/> Nigeria</p></div></div><div className="mx-auto mt-10 flex max-w-7xl justify-between border-t border-primary-foreground/15 px-5 pt-6 text-[11px] text-primary-foreground/55 lg:px-8"><span>© 2026 GonaAI. All rights reserved.</span><a href="#top">Back to top</a></div></footer>
  </div>;
}

function Field({label, children}:{label:string;children:ReactNode}) { return <label className="mb-5 block"><span className="mb-2 block text-xs font-extrabold">{label}</span>{children}</label>; }