// Static snapshot for the /demo partner dashboard.
// Generated by gonainsured-mvp/tools/export_demo.py - do not edit demo.json by hand.
import raw from "./demo.json";

export type Status = "normal" | "stress_detected" | "trigger_confirmed";
export type LayerKey = "ndvi" | "ndmi" | "rainfall";
export type Point = [string, number];

// result is absent in the portals' shared charts (no advisory / trigger shading).
export interface StageBand { name: string; start: string; end: string; result?: string }
export interface Series {
  xMin: string; xMax: string; today: string; stages: StageBand[];
  ndvi: Point[]; ndviNormal: Point[]; rain: Point[]; rainNormal: Point[]; rainProvisionalFrom: string | null;
}
export interface StageRow {
  name: string; start: string; end: string; evaluated: boolean;
  drought?: number | null; excessRain?: number | null; heat?: number | null; index?: number | null;
  ndviAnomaly?: number | null; scenes?: number | null; result?: string; provisional?: boolean;
  notes?: string[]; payout?: number;
}
export interface Report { created: string; stage: string; band: string; payout: number; ref: string; pdf: string }
export interface Message { sentAt: string | null; channel: string; status: string; text: string }
export interface HistoryRow { at: string | null; from: Status | null; to: Status; reason: string | null }
export interface Farmer {
  id: number; name: string; phone: string; cooperative: string; agent: string; lat: number; lon: number;
  zone: string; crop: string; plantingDate: string; status: Status; statusSince: string | null; stage: string;
  payout: number; lastEvaluated: string | null; series: Series; stages: StageRow[]; reports: Report[];
  messages: Message[]; history: HistoryRow[];
}
export interface MapLayer { src: string; vmin: number; vmax: number; unit: string; start: string; end: string; images: number }
export interface LegendInfo { title: string; what: string; classes: string[] }
export interface DemoData {
  asOf: string; zone: string; crop: string; farmers: Farmer[]; palette: string[];
  legend: Record<LayerKey, LegendInfo>;
  map: { bounds: [[number, number], [number, number]]; base: string; note: string; dates: Record<string, Record<LayerKey, MapLayer>> };
}

export const demo = raw as unknown as DemoData;

export const STATUS_LABEL: Record<Status, string> = {
  normal: "Normal", stress_detected: "Stress detected", trigger_confirmed: "Trigger confirmed",
};

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
export function fmtDay(iso: string): string {
  const d = new Date(iso + "T00:00:00Z");
  return `${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
}
export const pct = (v: number) => `${(v * 100).toFixed(1)}%`;
export const initials = (name: string) => name.split(" ").slice(0, 2).map(w => w[0] ?? "").join("").toUpperCase();
export const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
